//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kanban.Exception.ResourceErrorMessage", typeof(ResourceErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board already exists..
        /// </summary>
        public static string BOARD_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("BOARD_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board not found..
        /// </summary>
        public static string BOARD_NOT_FOUND {
            get {
                return ResourceManager.GetString("BOARD_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired code..
        /// </summary>
        public static string CODE_INVALID {
            get {
                return ResourceManager.GetString("CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color must be a valid hex color (e.g. #FFF or #FFFFFF)..
        /// </summary>
        public static string COLOR_INVALID_HEX {
            get {
                return ResourceManager.GetString("COLOR_INVALID_HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color is required..
        /// </summary>
        public static string COLOR_IS_REQUIRED {
            get {
                return ResourceManager.GetString("COLOR_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a column in that position..
        /// </summary>
        public static string COLUMN_ALREADY_IN_POSITION {
            get {
                return ResourceManager.GetString("COLUMN_ALREADY_IN_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column not found..
        /// </summary>
        public static string COLUMN_NOT_FOUND {
            get {
                return ResourceManager.GetString("COLUMN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already in use..
        /// </summary>
        public static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EMAIL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string INVALID_LOGIN {
            get {
                return ResourceManager.GetString("INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired token..
        /// </summary>
        public static string INVALID_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be at most 200 characters..
        /// </summary>
        public static string NAME_MAXIMUM_LENGTH {
            get {
                return ResourceManager.GetString("NAME_MAXIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be at least 3 characters..
        /// </summary>
        public static string NAME_MINIMUM_LENGTH {
            get {
                return ResourceManager.GetString("NAME_MINIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is invalid..
        /// </summary>
        public static string OLD_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("OLD_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PASSWORD_IS_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters..
        /// </summary>
        public static string PASSWORD_MINIMUM_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_MINIMUM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain lowercase letter..
        /// </summary>
        public static string PASSWORD_MUST_CONTAIN_LOWERCASE_LETTER {
            get {
                return ResourceManager.GetString("PASSWORD_MUST_CONTAIN_LOWERCASE_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain number..
        /// </summary>
        public static string PASSWORD_MUST_CONTAIN_NUMBER {
            get {
                return ResourceManager.GetString("PASSWORD_MUST_CONTAIN_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain special character.
        /// </summary>
        public static string PASSWORD_MUST_CONTAIN_SPECIAL_CHARACTER {
            get {
                return ResourceManager.GetString("PASSWORD_MUST_CONTAIN_SPECIAL_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain uppercase letter..
        /// </summary>
        public static string PASSWORD_MUST_CONTAIN_UPPERCASE_LETTER {
            get {
                return ResourceManager.GetString("PASSWORD_MUST_CONTAIN_UPPERCASE_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status must be a valid enum value..
        /// </summary>
        public static string STATUS_INVALID {
            get {
                return ResourceManager.GetString("STATUS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTask not found..
        /// </summary>
        public static string SUBTASK_NOT_FOUND {
            get {
                return ResourceManager.GetString("SUBTASK_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a task in that position..
        /// </summary>
        public static string TASK_ALREADY_IN_POSITION {
            get {
                return ResourceManager.GetString("TASK_ALREADY_IN_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task not found..
        /// </summary>
        public static string TASK_NOT_FOUND {
            get {
                return ResourceManager.GetString("TASK_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
