//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban.Communication.Email.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceEmailMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEmailMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kanban.Communication.Email.Resource.ResourceEmailMessage", typeof(ResourceEmailMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string RESET_ACCENT {
            get {
                return ResourceManager.GetString("RESET_ACCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not request a password reset, ignore this email. Your password remains the same..
        /// </summary>
        public static string RESET_ALERT {
            get {
                return ResourceManager.GetString("RESET_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received a request to reset your account password. Use the code below to continue the process..
        /// </summary>
        public static string RESET_BODY_1 {
            get {
                return ResourceManager.GetString("RESET_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security, never share this code with anyone. Our team will never ask for your access code..
        /// </summary>
        public static string RESET_BODY_2 {
            get {
                return ResourceManager.GetString("RESET_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires in &lt;strong&gt;10 minutes&lt;/strong&gt;.
        /// </summary>
        public static string RESET_CODE_EXPIRY {
            get {
                return ResourceManager.GetString("RESET_CODE_EXPIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string RESET_CODE_LABEL {
            get {
                return ResourceManager.GetString("RESET_CODE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}! Here is your recovery code.
        /// </summary>
        public static string RESET_HEADING {
            get {
                return ResourceManager.GetString("RESET_HEADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email was automatically generated. If you have questions, check your account settings..
        /// </summary>
        public static string RESET_NOTE {
            get {
                return ResourceManager.GetString("RESET_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study project of.
        /// </summary>
        public static string STUDY_PROJECT {
            get {
                return ResourceManager.GetString("STUDY_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string TITLE_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_RESET-PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Kanban project.
        /// </summary>
        public static string TITLE_WELCOME {
            get {
                return ResourceManager.GetString("TITLE_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WELCOME_ACCENT {
            get {
                return ResourceManager.GetString("WELCOME_ACCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was successfully created. This is a &lt;strong&gt;study project&lt;/strong&gt; developed by me (&lt;a href=&quot;https://jonatasgdec-portifolio.vercel.app/&quot; target=&quot;_blank&quot; style=&quot;color: #635FC7; text-decoration: underline; font-weight: 700;&quot;&gt;JonatasGdeC&lt;/a&gt;) to explore concepts of organization and productivity with a Kanban board..
        /// </summary>
        public static string WELCOME_BODY_1 {
            get {
                return ResourceManager.GetString("WELCOME_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to create boards, add tasks and test all available features. Your feedback is very valuable..
        /// </summary>
        public static string WELCOME_BODY_2 {
            get {
                return ResourceManager.GetString("WELCOME_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access the app.
        /// </summary>
        public static string WELCOME_CTA {
            get {
                return ResourceManager.GetString("WELCOME_CTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for testing the project {0}!.
        /// </summary>
        public static string WELCOME_HEADING {
            get {
                return ResourceManager.GetString("WELCOME_HEADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email was sent because you registered in the Kanban App. If it wasn&apos;t you, ignore this message..
        /// </summary>
        public static string WELCOME_NOTE {
            get {
                return ResourceManager.GetString("WELCOME_NOTE", resourceCulture);
            }
        }
    }
}
